apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analysis-templates
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/platform-demo
    targetRevision: HEAD
    path: platform-config/templates/analysis-templates
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
