apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # For local development, use the local path
    # For production, this would be your Git repo URL
    repoURL: https://github.com/YOUR_USERNAME/platform-demo
    targetRevision: HEAD
    path: applications/demo-app-1/manifests/demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
